function [fitresult, gof] = spinesurf(x, y, z)
%CREATESURFACEFIT(X,Y,Z)
%  Fit surface to data.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Input : y
%      Z Output: z
%  Output:
%      fitresult : an sfit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, SFIT.

%  Auto-generated by MATLAB on 11-Jul-2014 01:41:14


%% Fit: 'untitled fit 1'.
[xInput, yInput, zOutput] = prepareSurfaceData( x, y, z );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xInput, yInput], zOutput, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'radial distance' );

% Plot fit with data.
subplot('Position',[.08 .53 .87 .40]);
h = plot( fitresult, [xInput, yInput], zOutput, 'Style', 'PredObs' );
%legend( h, 'radial distance', 'xyz', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x' );
ylabel( 'y' );
zlabel( 'z' );
grid on
view( -53.5, 74 );

% Make contour plot.
subplot('Position',[.08 .07 .87 .40]);
h = plot( fitresult, [xInput, yInput], zOutput, 'Style', 'Contour' );
legend( h, 'radial distance', 'xyz', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x' );
ylabel( 'y' );
grid on


