function [fitresult, gof] = spinesurf2(x, y, z)
%CREATESURFACEFIT(X,Y,Z)
%  Fit surface to data.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Input : y
%      Z Output: z
%  Output:
%      fitresult : an sfit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, SFIT.

%  Auto-generated by MATLAB on 11-Jul-2014 18:35:06

%% Fit: 'untitled fit 6'.
[xInput, yInput, zOutput] = prepareSurfaceData( x, y, z );

% Set up fittype and options.
ft = fittype( 'loess' );
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xInput, yInput], zOutput, ft, opts );

% Plot fit with data.
figure( 'Name', 'radial distance' );
set(gcf,'Color',[1,1,1])
set(gcf,'OuterPosition',[400 200 500 800])

subplot('Position',[.08 .53 .87 .40]);
h1 = plot( fitresult, [xInput, yInput], zOutput );
% set(h1,'Marker','o','MarkerSize',5,...
% 	'MarkerEdgeColor',[.1 .1 .9],'MarkerFaceColor',[.1 .9 .9]);
haxes=axis;
xlim([haxes(1:2)*.8 ]);
ylim([haxes(3:4)*.8 ]);
zlim([haxes(5:6)*.8 ]);
xlabel( 'x' );
ylabel( 'y' );
zlabel( 'z' );
grid on
box off
view( -36, 36 );

% Make contour plot.
subplot('Position',[.08 .07 .87 .40]);
h2 = plot( fitresult, [xInput, yInput], zOutput, 'Style', 'Contour' );
legend( h2, 'radial distance', 'xyz', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x' );
ylabel( 'y' );
grid on







